version: '3.8'
services:
  tap-eodhistoricaldata:
    restart: always
    build:
      context: ./docker/meltano/tap-eodhistoricaldata
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./docker/meltano/tap-eodhistoricaldata:/tap-eodhistoricaldata
  tap-polygon:
    restart: always
    build:
      context: ./docker/meltano/tap-polygon
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./docker/meltano/tap-polygon:/tap-polygon
  tap-coingecko:
    restart: always
    build:
      context: ./docker/meltano/tap-coingecko
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./docker/meltano/tap-coingecko:/tap-coingecko
