version: '3.8'
services:
  test-tap-eodhistoricaldata:
    restart: always
    build:
      context: ./docker/meltano/tap-eodhistoricaldata
      dockerfile: test.Dockerfile
  test-tap-polygon:
    restart: always
    build:
      context: ./docker/meltano/tap-polygon
      dockerfile: test.Dockerfile