#!/bin/bash

while ! PGPASSWORD=$PG_PASSWORD pg_isready -h $PG_HOST -p $PG_PORT -U $PG_USERNAME; do sleep 1; done

find /init.d -maxdepth 1 -type f | sort | while read -r i; do
  chmod +x $i
  $i
done

export TAP_POSTGRES_SYNC_FUNDAMENTALS_HOST="$TAP_POSTGRES_SYNC_HOST"
export TAP_POSTGRES_SYNC_FUNDAMENTALS_PORT="$TAP_POSTGRES_SYNC_PORT"
export TAP_POSTGRES_SYNC_FUNDAMENTALS_USER="$TAP_POSTGRES_SYNC_USER"
export TAP_POSTGRES_SYNC_FUNDAMENTALS_PASSWORD="$TAP_POSTGRES_SYNC_PASSWORD"
export TAP_POSTGRES_SYNC_FUNDAMENTALS_DBNAME="$TAP_POSTGRES_SYNC_DBNAME"
export TAP_POSTGRES_SYNC_FUNDAMENTALS_FILTER_SCHEMAS="$TAP_POSTGRES_SYNC_FILTER_SCHEMAS"

export TAP_POSTGRES_SYNC_OPTIONS_HOST="$TAP_POSTGRES_SYNC_HOST"
export TAP_POSTGRES_SYNC_OPTIONS_PORT="$TAP_POSTGRES_SYNC_PORT"
export TAP_POSTGRES_SYNC_OPTIONS_USER="$TAP_POSTGRES_SYNC_USER"
export TAP_POSTGRES_SYNC_OPTIONS_PASSWORD="$TAP_POSTGRES_SYNC_PASSWORD"
export TAP_POSTGRES_SYNC_OPTIONS_DBNAME="$TAP_POSTGRES_SYNC_DBNAME"
export TAP_POSTGRES_SYNC_OPTIONS_FILTER_SCHEMAS="$TAP_POSTGRES_SYNC_FILTER_SCHEMAS"

export TARGET_POSTGRES_SMALL_BATCH_HOST="$TARGET_POSTGRES_HOST"
export TARGET_POSTGRES_SMALL_BATCH_PORT="$TARGET_POSTGRES_PORT"
export TARGET_POSTGRES_SMALL_BATCH_USER="$TARGET_POSTGRES_USER"
export TARGET_POSTGRES_SMALL_BATCH_PASSWORD="$TARGET_POSTGRES_PASSWORD"
export TARGET_POSTGRES_SMALL_BATCH_DBNAME="$TARGET_POSTGRES_DBNAME"
export TARGET_POSTGRES_SMALL_BATCH_SCHEMA="$TARGET_POSTGRES_SCHEMA"

meltano "$@"
