version: 1
send_anonymous_usage_stats: false
project_id: 36bd814f-1cb5-402a-8d9c-d3219c38f2b3
plugins:
  extractors:
    - name: tap-eodhistoricaldata
      namespace: tap_eodhistoricaldata
      pip_url: /tap-eodhistoricaldata
    - name: tap-eodhistoricaldata-prices
      inherit_from: tap-eodhistoricaldata

    - name: tap-polygon
      namespace: tap_polygon
      pip_url: /tap-polygon

    - name: tap-coingecko
      namespace: tap_coingecko
      pip_url: /tap-coingecko
    - name: tap-coingecko-realtime
      inherit_from: tap-coingecko

    - name: tap-csv

    - name: tap-postgres
      pip_url: git+https://github.com/asmisha/pipelinewise-tap-postgres.git@refresh-streams-schema
    - name: tap-postgres-sync
      inherit_from: tap-postgres
    - name: tap-postgres-sync-fundamentals
      inherit_from: tap-postgres-sync
    - name: tap-postgres-sync-options
      inherit_from: tap-postgres-sync

    - name: tap-postgres-search
      inherit_from: tap-postgres

    - name: tap-postgres-analytics
      inherit_from: tap-postgres
    - name: tap-postgres-analytics-small-batch
      inherit_from: tap-postgres-analytics
    - name: tap-postgres-analytics-bigquery
      inherit_from: tap-postgres-analytics
    - name: tap-postgres-analytics-bigquery-small-batch
      inherit_from: tap-postgres-analytics

    - name: tap-postgres-website
      inherit_from: tap-postgres

    - name: tap-postgres-history
      inherit_from: tap-postgres
    - name: tap-postgres-history-reused
      inherit_from: tap-postgres-history
    - name: tap-postgres-history-daily
      inherit_from: tap-postgres-history
    - name: tap-postgres-history-weekly
      inherit_from: tap-postgres-history

    - name: tap-bigquery
      variant: anelendata
      pip_url: tap-bigquery

  loaders:
    - name: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres
    - name: target-postgres-small-batch
      inherit_from: target-postgres

    - name: target-postgres-analytics
      inherit_from: target-postgres
    - name: target-postgres-analytics-small-batch
      inherit_from: target-postgres-small-batch

    - name: target-algolia
      namespace: target-algolia
      pip_url: /target-algolia

    - name: target-s3-csv
      pip_url: pipelinewise-target-s3-csv
      namespace: pipelinewise-target-s3-csv
      executable: target-s3-csv
    - name: target-s3-csv-history
      inherit_from: target-s3-csv

    - name: target-bigquery
      variant: transferwise
      pip_url: pipelinewise-target-bigquery
    - name: target-bigquery-small-batch
      inherit_from: target-bigquery

#  transformers:
#    - name: dbt
#      pip_url: dbt-postgres==1.3.1
#  orchestrators:
#    - name: airflow
#      pip_url: psycopg2-binary==2.9.5 apache-airflow==2.5.0 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-${MELTANO__PYTHON_VERSION}.txt

  utilities:
  - name: dbt-postgres
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-postgres~=1.3.0 git+https://github.com/meltano/dbt-ext.git@main

  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow[postgres]==2.3.3
      --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-${MELTANO__PYTHON_VERSION}.txt

environments:
  - name: dev
