version: 1
send_anonymous_usage_stats: false
project_id: 36bd814f-1cb5-402a-8d9c-d3219c38f2b3
plugins:
  extractors:
    - name: tap-eodhistoricaldata
      namespace: tap_eodhistoricaldata
      pip_url: /tap-eodhistoricaldata
    - name: tap-eodhistoricaldata-prices
      inherit_from: tap-eodhistoricaldata

    - name: tap-polygon
      namespace: tap_polygon
      pip_url: /tap-polygon

    - name: tap-coingecko
      namespace: tap_coingecko
      pip_url: /tap-coingecko
    - name: tap-coingecko-realtime
      inherit_from: tap-coingecko

    - name: tap-csv

    - name: tap-postgres
    - name: tap-postgres-sync
      inherit_from: tap-postgres
    - name: tap-postgres-sync-fundamentals
      inherit_from: tap-postgres
    - name: tap-postgres-sync-options
      inherit_from: tap-postgres

    - name: tap-postgres-search
      inherit_from: tap-postgres

    - name: tap-postgres-analytics
      inherit_from: tap-postgres
    - name: tap-postgres-analytics-small-batch
      inherit_from: tap-postgres-analytics

    - name: tap-postgres-website
      inherit_from: tap-postgres

    - name: tap-postgres-history
      inherit_from: tap-postgres
    - name: tap-postgres-history-reused
      inherit_from: tap-postgres-history
    - name: tap-postgres-history-daily
      inherit_from: tap-postgres-history
    - name: tap-postgres-history-weekly
      inherit_from: tap-postgres-history

  loaders:
    - name: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres
    - name: target-postgres-small-batch
      inherit_from: target-postgres

    - name: target-postgres-analytics
      inherit_from: target-postgres
    - name: target-postgres-analytics-small-batch
      inherit_from: target-postgres-small-batch

    - name: target-algolia
      namespace: target-algolia
      pip_url: /target-algolia

    - name: target-s3-csv
      pip_url: pipelinewise-target-s3-csv
      namespace: pipelinewise-target-s3-csv
      executable: target-s3-csv
    - name: target-s3-csv-history
      inherit_from: target-s3-csv

  transformers:
    - name: dbt
      pip_url: dbt-postgres==1.1.1
  orchestrators:
    - name: airflow
      pip_url: psycopg2-binary==2.9.3 apache-airflow==2.3.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.3.2/constraints-${MELTANO__PYTHON_VERSION}.txt
