name: "Publish"

on:
  release:
    types:
      - published
      - edited

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker environment
        run: (docker buildx ls | grep docker-container || docker buildx create --use) && docker run -i --rm --privileged tonistiigi/binfmt --install all

      - name: Authorize Docker
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 217303665077.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Publish
        run: make build
        env:
          BUILD_FLAGS: "--push"

#      - name: Publish
#        if: startsWith(github.ref, 'refs/tags/')
#        run: make publish

