name: "Test"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        id: test
        continue-on-error: true
        run: make test 2>&1

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request' && steps.test.outcome == 'success'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Tests: ✅ \`${{ steps.test.outcome }}\`
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Tests Status
        if: steps.test.outcome == 'failure'
        run: make test-clean && exit 1
